import { Routes } from '@angular/router';
import { BranchMasterComponent } from './branch-master/branch-master.component';
import { RoleMasterComponent } from './role-master/role-master.component';
import { UserMasterComponent } from './user-master/user-master.component';
import { LoanMasterComponent } from './loan-master/loan-master.component';
import { AuditSectionMasterComponent } from './audit-section-master/audit-section-master.component';
import { EmployeeMasterComponent } from './employee-master/employee-master.component';
import { AuditUnitMasterComponent } from './audit-unit-master/audit-unit-master.component';
import { PasswordPolicyMasterComponent } from './password-policy-master/password-policy-master.component';
import { MenuMasterComponent } from './menu-master/menu-master.component';
import { AuditTargetMasterComponent } from './audit-unit-master/audit-target-master.component';
import { AuditSchemeMasterComponent } from './audit-scheme-master/audit-scheme-master.component';
import { AuditQuestionSetMasterComponent } from './audit-question-master/audit-question-set-master.component';
import { AuditQuestionSetHeaderMasterComponent } from './audit-question-master/audit-question-set-header-master.component';
import { AuditQuestionMasterComponent } from './audit-question-master/audit-question-master.component';
import { AuditCategoryMasterComponent } from './audit-category-master/audit-category-master.component';
import { BorderAreaMasterComponent } from './border-area-master/border-area-master.component';
import { ManageAssessmentMasterComponent } from './manage-assement-master/manage-assement-master-main.compoent';
import { AuditAnnexureMasterComponent } from './audit-annexure-master/audit-annexure-master.component';
import { AuditAnnexureColumnsComponent } from './audit-annexure-master/audit-annexure-columns-master.component';
import { RiskCategoryComponent } from './risk-masters/risk-category/risk-category-master.component';
import { RiskCategoryWeightComponent } from './risk-masters/risk-category/risk-category-weights.component';
import { RiskControlComponent } from './risk-masters/risk-control/risk-control-master.component';
import { RiskControlKeyAspectComponent } from './risk-masters/risk-control/risk-control-key-aspect.component';
import { RiskCompositeComponent } from './risk-masters/risk-composite/risk-composite-master.component';
import { RiskMatrixComponent } from './risk-masters/risk-matrix/risk-matrix.component';
import { RiskMatrixConfigComponent } from './risk-masters/risk-matrix/risk-matrix-config.component';
import { BranchRatingComponent } from './risk-masters/branch-rating/branch-rating.component';
import { BranchRatingListComponent } from './risk-masters/branch-rating/branch-rating-list.component.ts';
import { PeriodwiseQuestionsMasterComponent } from './periodwise-questions-master/periodwise-questions-master';


export const ADMIN_ROUTES: Routes = [
    { path: 'branch-master', component: BranchMasterComponent },
    { path: 'role-master', component: RoleMasterComponent },
    { path: 'user-master', component: UserMasterComponent },
    { path: 'loan-type-master', component: LoanMasterComponent },
    { path: 'audit-section-master', component: AuditSectionMasterComponent },
    { path: 'employee-master', component: EmployeeMasterComponent },
    { path: 'audit-unit-master', component: AuditUnitMasterComponent },
    { path: 'password-policy-master', component: PasswordPolicyMasterComponent },
    { path: 'menu-master', component: MenuMasterComponent },
    { path: 'audit-unit-target-master/:auditUnitId', component: AuditTargetMasterComponent },
    { path: 'audit-scheme-master', component: AuditSchemeMasterComponent },
    { path: 'question-set-master', component: AuditQuestionSetMasterComponent },
    { path: 'question-header-master/:setId', component: AuditQuestionSetHeaderMasterComponent },
    { path: 'question-master/:setId/:headerId', component: AuditQuestionMasterComponent },
    { path: 'question-master/:setId', component: AuditQuestionMasterComponent },
    { path: 'audit-category-master', component: AuditCategoryMasterComponent },
    { path: 'broader-area-master', component: BorderAreaMasterComponent },
    { path: 'manage-assessment-master', component: ManageAssessmentMasterComponent },
    { path: 'periodwise-questions-master', component: PeriodwiseQuestionsMasterComponent },
    { path: 'audit-annexure-master', component: AuditAnnexureMasterComponent },
    { path: 'audit-annexure-master/:id/columns', component: AuditAnnexureColumnsComponent },
    { path: 'risk-categories', component: RiskCategoryComponent },
    { path: 'risk-categories/:id/weights', component: RiskCategoryWeightComponent },
    { path: 'risk-controls', component: RiskControlComponent },
    { path: 'risk-controls/:id/key-aspects', component: RiskControlKeyAspectComponent },
    { path: 'risk-composites', component: RiskCompositeComponent },
    { path: 'risk-matrix', component: RiskMatrixComponent },
    { path: 'risk-matrix/:id', component: RiskMatrixConfigComponent },
    { path: 'branch-rating', component: BranchRatingComponent },
    { path: 'branch-rating/:id', component: BranchRatingListComponent },
];
